@startuml
left to right direction

actor "Продавец\n(кассир)" as Cashier
actor "Менеджер\n(товаровед)" as Manager

rectangle "Система учёта возвратов товаров" {
usecase "Вход в систему" as UC1
usecase "Найти продажу (чек)" as UC2
usecase "Оформить возврат" as UC3
usecase "Указать причину возврата" as UC4
usecase "Просмотреть список возвратов" as UC5
usecase "Регистрация в системе" as UC6
usecase "Регистрация кассиров" as UC7
usecase "Проверить состояние товара" as UC8
usecase "Принять решение\nпо возврату" as UC9
usecase "Изменить остатки товара" as UC10
usecase "Сформировать отчёт\nпо возвратам" as UC11
}

Cashier --> UC1
Cashier --> UC2
Cashier --> UC3
Cashier --> UC4
Cashier --> UC5

Manager --> UC1
Manager --> UC5
Manager --> UC6
Manager --> UC7
Manager --> UC8
Manager --> UC9
Manager --> UC10
Manager --> UC11
@enduml